### ISSUE TITLE
Error NullException bila username dan password kosong di HTTP Header

### ISSUE THREAD

**Issue by mrizkir** [diskominfokepri/kiisgateway#4]
Seharusnya terdapat mekanisme untuk mengecek apakah username dan password telah ada di Header HTTP; karena bila tidak ada maka akan muncul error : 

```
Caused by: 
java.lang.NullPointerException
	at id.go.kepriprov.kiisgateway.lib.Helper.createSHA1(Helper.java:27)
	at id.go.kepriprov.kiisgateway.lib.Authentication.checkUsernameAndPassword(Authentication.java:19)
	at id.go.kepriprov.kiisgateway.services.EntryPoint.query(EntryPoint.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by mrizkir** [comment]
fixed.
